### ISSUE TITLE
请问怎么使用，客服端是哪个

### ISSUE THREAD

**Issue by Shenxiaoy** [Steve-ShadowsocksR/-SSR-#1]

**Comment by Steve-ShadowsocksR** [comment]
你好，请问你有什么问题吗？




------------------ 原始邮件 ------------------
发件人: "申晓宇"<notifications@github.com>;
发送时间: 2019年8月16日(星期五) 下午3:08
收件人: "Steve-ShadowsocksR/-SSR-"<-SSR-@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Steve-ShadowsocksR/-SSR-] 请问怎么使用，客服端是哪个 (#1)

**Comment by Shenxiaoy** [comment]
我想问一下怎么使用你分享的ssr

**Comment by Steve-ShadowsocksR** [comment]
首先下载ssr客户端，再复制ssr链接并导入客户端，最后即可使用了。
